"""empty message

Revision ID: 0322921283db
Revises: 4f099624d686
Create Date: 2023-09-24 17:23:30.682547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0322921283db'
down_revision = '4f099624d686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_venue', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('seeking_venue')

    # ### end Alembic commands ###
