"""empty message

Revision ID: 4f099624d686
Revises: 4f28c9172ef1
Create Date: 2023-07-25 16:16:02.352937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f099624d686'
down_revision = '4f28c9172ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('Show_artis_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Artist', ['artist_id'], ['id'])
        batch_op.drop_column('artis_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artis_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Show_artis_id_fkey', 'Artist', ['artis_id'], ['id'])
        batch_op.drop_column('artist_id')

    # ### end Alembic commands ###
